name: Test NimYAML

concurrency:
  group: Test NimYAML
  cancel-in-progress: true

on: [push, pull_request]

jobs:
  test:
    name: test (${{ matrix.platform.os }}, ${{ matrix.nim-version }}, ${{ matrix.mm }})
    runs-on: ${{ matrix.platform.os }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          # - os: ubuntu-latest
          - os: windows-latest
          # - os: macos-latest
        nim-version:
          - stable
          # - devel
        mm:
          - refc
          # - arc
          # - orc
    steps:
      - uses: actions/checkout@v3
      - uses: './.github/actions/vscode'
      - uses: './.github/actions/nim'
        with:
          version: ${{ matrix.nim-version }}
      - run: nimble install -y
      - run: |
          nim test --mm:${{ matrix.mm }}

      - if: matrix.platform.os == 'ubuntu-latest'
        uses: './.github/actions/memcheck'
        with:
          source-path: test/tests.nim
          program-path: test/tests
